service: coreApi

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: core/create.create
    events:
      - http:
          path: core
          method: post
          cors: true

  list:
    handler: core/list.list
    events:
      - http:
          path: core
          method: get
          cors: true

  get:
    handler: core/get.get
    events:
      - http:
          path: core/{id}
          method: get
          cors: true

  update:
    handler: core/update.update
    events:
      - http:
          path: core/{id}
          method: put
          cors: true

  delete:
    handler: core/delete.delete
    events:
      - http:
          path: core/{id}
          method: delete
          cors: true

resources:
  Resources:
    PetsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain # Keeps around the DynamoDB resource when we redeploy/destroy
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}